name: Accessibility Audit
on:
  pull_request:
    paths:
      - '**/*.tsx'
      - '**/*.jsx'

jobs:
  accessibility-audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: AlexJackson01/rn-a11y-audit/.github/actions/a11y-audit@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}